#!/bin/sh

set -e

case "$1" in
  install|upgrade)
    if [ -e /etc/lightdm/lightdm-gtk-greeter.conf ]; then
        cp /etc/lightdm/lightdm-gtk-greeter.conf /etc/lightdm/lightdm-gtk-greeter.conf.$(date +%Y%m%H%M%S)
    fi
    echo -ne '[greeter]'\\n\
    'background = #stretched:/usr/share/backgrounds/MXLinux/lightdm/myreflections_by_ant_ony/login.jpg'\\n\
    'theme-name = Blackbird'\\n\
    'xft-antialias = true'\\n\
    'xft-hintstyle = hintfull'\\n\
    'xft-rgba = rgb'\\n\
    'icon-theme-name = Papirus'\\n\
    'hide-user-image = false'\\n\
    'indicators = ~host;~spacer;~session;~power;~layout;~a11y'\\n\
    'keyboard = onboard'\\n\
    'a11y-states = ~keyboard'\\n\
    'position = 50%,center 65%,center'\\n\
    ''\\n | sed 's/^ //;s/^-ne //'>/etc/lightdm/lightdm-gtk-greeter.conf
  ;;
  *)
    :
  ;;
esac

#DEBHELPER#

exit 0
